import { describe, expect, test } from "bun:test";
import { DatabaseInspector } from "../core/schema/inspector";
import {
  parsePostgresForeignServerCatalogOptions,
} from "../utils/postgres-foreign-server";

function createClient(handler: (sql: string, params?: unknown[]) => { rows: unknown[] }): any {
  return {
    query: async function (sql: string, params?: unknown[]) {
      return handler(sql, params);
    },
  };
}

describe("Advanced SQL object inspector", function () {
  test(
    "rejects malformed or duplicate foreign server catalog options",
    function () {
      expect(function parseMalformedOption() {
        parsePostgresForeignServerCatalogOptions(
          ["missing_separator"],
          "remote"
        );
      }).toThrow(/malformed catalog option/i);
      expect(function parseDuplicateOption() {
        parsePostgresForeignServerCatalogOptions(
          ["host=one", "host=two"],
          "remote"
        );
      }).toThrow(/duplicate catalog option/i);
    }
  );

  test("renders partition identity columns without the default LOGGED option", function () {
    const inspector = new DatabaseInspector() as any;
    const row = {
      column_name: "id",
      pg_type: "integer",
      attidentity: "d",
      identity_sequence_name: "events_id_seq",
      identity_sequence_schema: "public",
      identity_start: "7",
      identity_increment: "3",
      identity_cycle: false,
    };

    const logged = inspector.buildColumnDefinition({
      ...row,
      identity_sequence_persistence: "p",
    });
    expect(logged).toStartWith('"id" integer GENERATED BY DEFAULT AS IDENTITY (');
    expect(logged).toContain("START WITH 7");
    expect(logged).not.toContain("LOGGED");

    const unlogged = inspector.buildColumnDefinition({
      ...row,
      identity_sequence_persistence: "u",
    });
    expect(unlogged).toContain("UNLOGGED");
  });

  test("inspects only portable default privilege deviations", async function () {
    const inspector = new DatabaseInspector() as any;
    const client = createClient(function (sql) {
      expect(sql).toContain("FROM pg_default_acl");
      expect(sql).toContain("WHEN defaults.defaclobjtype = 'S'");
      expect(sql).toContain("THEN 's'::\"char\"");
      expect(sql).toContain("ELSE NULL::aclitem[]");
      expect(sql).toContain("COALESCE(actual.is_grantable, false)");
      expect(sql).toContain(") privilege ON true");
      return {
        rows: [
          {
            owner_name: "object_owner",
            schema_name: null,
            object_type: "f",
            privilege_type: "EXECUTE",
            grantee_is_public: true,
            grantee_name: "PUBLIC",
            actual_granted: false,
            is_grantable: false,
            baseline_granted: true,
            grantor_name: null,
          },
          {
            owner_name: "object_owner",
            schema_name: null,
            object_type: "r",
            privilege_type: "SELECT",
            grantee_is_public: false,
            grantee_name: "reader",
            actual_granted: true,
            is_grantable: false,
            baseline_granted: false,
            grantor_name: "object_owner",
          },
          {
            owner_name: "object_owner",
            schema_name: "app",
            object_type: "r",
            privilege_type: "INSERT",
            grantee_is_public: false,
            grantee_name: "reader",
            actual_granted: true,
            is_grantable: true,
            baseline_granted: false,
            grantor_name: "object_owner",
          },
          {
            owner_name: "object_owner",
            schema_name: null,
            object_type: "r",
            privilege_type: "MAINTAIN",
            grantee_is_public: false,
            grantee_name: "reader",
            actual_granted: true,
            is_grantable: false,
            baseline_granted: false,
            grantor_name: "object_owner",
          },
          {
            owner_name: "object_owner",
            schema_name: null,
            object_type: "L",
            privilege_type: "SELECT",
            grantee_is_public: false,
            grantee_name: "reader",
            actual_granted: true,
            is_grantable: false,
            baseline_granted: false,
            grantor_name: "object_owner",
          },
        ],
      };
    });

    const objects = await inspector.getCurrentDefaultPrivilegeObjects(client);

    expect(objects).toHaveLength(3);
    expect(objects[0]).toMatchObject({
      kind: "default-privilege",
      key:
        "default-privilege:ALTER DEFAULT PRIVILEGES FOR ROLE \"object_owner\" " +
        "GRANT EXECUTE ON ROUTINES TO PUBLIC;",
      createStatement:
        "ALTER DEFAULT PRIVILEGES FOR ROLE \"object_owner\" " +
        "REVOKE EXECUTE ON ROUTINES FROM PUBLIC RESTRICT;",
      dropStatement:
        "ALTER DEFAULT PRIVILEGES FOR ROLE \"object_owner\" " +
        "GRANT EXECUTE ON ROUTINES TO PUBLIC;",
      defaultPrivilegeDefinition: {
        granted: false,
        grantable: false,
        baselineGranted: true,
      },
      dependencies: ["role:object_owner"],
    });
    expect(objects[1]).toMatchObject({
      createStatement:
        "ALTER DEFAULT PRIVILEGES FOR ROLE \"object_owner\" " +
        "GRANT SELECT ON TABLES TO \"reader\";",
      dropStatement:
        "ALTER DEFAULT PRIVILEGES FOR ROLE \"object_owner\" " +
        "REVOKE SELECT ON TABLES FROM \"reader\" RESTRICT;",
      dependencies: ["role:object_owner", "role:reader"],
    });
    expect(objects[2]).toMatchObject({
      schema: "app",
      createStatement:
        "ALTER DEFAULT PRIVILEGES FOR ROLE \"object_owner\" IN SCHEMA \"app\" " +
        "GRANT INSERT ON TABLES TO \"reader\" WITH GRANT OPTION;",
      dropStatement:
        "ALTER DEFAULT PRIVILEGES FOR ROLE \"object_owner\" IN SCHEMA \"app\" " +
        "REVOKE INSERT ON TABLES FROM \"reader\" RESTRICT;",
      defaultPrivilegeDefinition: {
        granted: true,
        grantable: true,
        baselineGranted: false,
      },
    });
  });

  test("rejects default privileges granted by a non-owner role", async function () {
    const inspector = new DatabaseInspector() as any;
    const client = createClient(function () {
      return {
        rows: [{
          owner_name: "object_owner",
          schema_name: null,
          object_type: "r",
          privilege_type: "SELECT",
          grantee_is_public: false,
          grantee_name: "reader",
          actual_granted: true,
          is_grantable: false,
          baseline_granted: false,
          grantor_name: "grant_manager",
        }],
      };
    });

    await expect(
      inspector.getCurrentDefaultPrivilegeObjects(client)
    ).rejects.toThrow(/granted by non-owner role 'grant_manager'/i);
  });

  test("inspects issue 112 object families from a live database", async function () {
    const inspector = new DatabaseInspector();
    const client = createClient(function (sql, params) {
      if (sql.includes("pg_get_partkeydef")) {
        expect(params).toEqual([["public"]]);
        return {
          rows: [
            {
              oid: 101,
              table_name: "accounts",
              schema_name: "public",
              partition_key: "RANGE (region_id)",
            },
          ],
        };
      }

      if (sql.includes("pg_attribute a") && params?.[0] === "accounts") {
        return {
          rows: [
            {
              column_name: "id",
              pg_type: "integer",
              is_nullable: false,
              column_default: null,
              attgenerated: "",
              generation_expression: null,
            },
            {
              column_name: "region_id",
              pg_type: "integer",
              is_nullable: false,
              column_default: null,
              attgenerated: "",
              generation_expression: null,
            },
          ],
        };
      }

      if (sql.includes("WHERE conrelid = $1")) {
        expect(params).toEqual([101]);
        return {
          rows: [
            {
              conname: "accounts_pkey",
              definition: "PRIMARY KEY (id)",
            },
          ],
        };
      }

      if (sql.includes("c.relispartition")) {
        expect(params).toEqual([["public"]]);
        return {
          rows: [
            {
              table_name: "accounts_eu",
              schema_name: "public",
              parent_name: "accounts",
              parent_schema: "public",
              partition_bound: "FOR VALUES FROM (0) TO (100)",
            },
          ],
        };
      }

      if (sql.includes("relrowsecurity")) {
        expect(params).toEqual([["public"]]);
        return {
          rows: [
            {
              table_name: "users",
              schema_name: "public",
              row_security_enabled: true,
              row_security_forced: true,
            },
          ],
        };
      }

      if (sql.includes("FROM pg_policy")) {
        expect(params).toEqual([["public"]]);
        return {
          rows: [
            {
              policy_name: "tenant_policy",
              table_name: "users",
              schema_name: "public",
              policy_command: "r",
              is_permissive: true,
              using_expression: "(tenant_id = current_setting('app.tenant_id'::text)::integer)",
              with_check_expression: "(tenant_id > 0)",
              policy_roles: ["app_reader"],
            },
          ],
        };
      }

      if (sql.includes("t.typtype = 'd'")) {
        expect(params).toEqual([["public"]]);
        return {
          rows: [
            {
              oid: 201,
              type_name: "email_address",
              schema_name: "public",
              base_type: "text",
              base_type_kind: "b",
              base_type_schema: "pg_catalog",
              base_type_name: "text",
              collation_name: "C",
              collation_schema: "pg_catalog",
              is_not_null: true,
              default_value: "'n/a'::text",
              attribute_dependents: [
                {
                  schema: "public",
                  relation: "users",
                  attribute: "email",
                  relationKind: "r",
                },
              ],
              type_dependents: [
                { schema: "public", name: "verified_email", kind: "domain" },
              ],
              routine_dependents: [
                {
                  schema: "public",
                  name: "normalize_email",
                  kind: "function",
                  identityArguments: "email_address",
                },
              ],
            },
          ],
        };
      }

      if (sql.includes("WHERE contypid = $1")) {
        expect(params).toEqual([201]);
        return {
          rows: [
            {
              conname: "email_address_check",
              definition: "CHECK ((position(('@'::text), VALUE) > 1))",
              expression: "position(('@'::text), VALUE) > 1",
              is_validated: false,
            },
          ],
        };
      }

      if (sql.includes("WITH RECURSIVE dependent_types")) {
        expect(params).toEqual([201]);
        return { rows: [{ has_container_dependents: true }] };
      }

      if (sql.includes("FROM pg_range")) {
        expect(params).toEqual([["public"]]);
        return {
          rows: [
            {
              type_name: "price_window",
              schema_name: "public",
              subtype_name: "numeric",
              subtype_kind: "b",
              subtype_schema: "pg_catalog",
              subtype_type_name: "numeric",
              subtype_opclass_name: "numeric_ops",
              subtype_opclass_bare_name: "numeric_ops",
              subtype_opclass_schema: "pg_catalog",
              subtype_opclass_is_default: false,
              collation_name: "\"C\"",
              collation_bare_name: "C",
              collation_schema: "pg_catalog",
              canonical_name: "public.price_window_canonical",
              canonical_bare_name: "price_window_canonical",
              canonical_schema: "public",
              diff_name: "public.price_window_diff",
              diff_bare_name: "price_window_diff",
              diff_schema: "public",
              multirange_name: "price_windows",
              multirange_schema: "public",
              attribute_dependents: [],
              type_dependents: [
                { schema: "public", name: "bounded_price", kind: "domain" },
              ],
              routine_dependents: [],
            },
          ],
        };
      }

      if (sql.includes("srvoptions as server_options")) {
        return {
          rows: [
            {
              server_name: "analytics_server",
              fdw_name: "postgres_fdw",
              owner_name: "server_owner",
              server_type: "postgresql",
              server_version: "14",
              server_options: ["host=127.0.0.1", "dbname=analytics", "port=5432"],
            },
          ],
        };
      }

      if (sql.includes("t.tgconstraint <> 0")) {
        expect(params).toEqual([["public"]]);
        return {
          rows: [
            {
              trigger_name: "audit_users_trigger",
              table_name: "users",
              schema_name: "public",
              trigger_definition: "CREATE CONSTRAINT TRIGGER audit_users_trigger AFTER INSERT ON public.users DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.audit_users_trigger()",
            },
          ],
        };
      }

      if (sql.includes("FROM pg_event_trigger")) {
        return {
          rows: [
            {
              trigger_name: "audit_ddl",
              event_name: "ddl_command_end",
              trigger_tags: ["CREATE TABLE"],
              function_name: "audit_ddl",
              function_schema: "public",
            },
          ],
        };
      }

      if (sql.includes("FROM pg_roles")) {
        return {
          rows: [
            {
              role_name: "app_reader",
              can_login: false,
              is_superuser: false,
              can_create_db: false,
              can_create_role: false,
              can_inherit: false,
              can_replicate: false,
              can_bypass_rls: false,
              connection_limit: 5,
            },
            {
              role_name: "app_user",
              can_login: true,
              is_superuser: false,
              can_create_db: false,
              can_create_role: false,
              can_inherit: true,
              can_replicate: false,
              can_bypass_rls: false,
              connection_limit: -1,
            },
          ],
        };
      }

      if (sql.includes("aclexplode(c.relacl)")) {
        expect(params).toEqual([["public"]]);
        return {
          rows: [
            {
              schema_name: "public",
              object_name: "users",
              object_type: "TABLE",
              grantee_name: "app_reader",
              privilege_type: "SELECT",
              is_grantable: false,
            },
          ],
        };
      }

      if (sql.includes("aclexplode(n.nspacl)")) {
        expect(params).toEqual([["public"]]);
        return {
          rows: [
            {
              schema_name: "public",
              grantee_name: "app_reader",
              privilege_type: "USAGE",
              is_grantable: false,
            },
          ],
        };
      }

      if (sql.includes("aclexplode(s.srvacl)")) {
        return {
          rows: [
            {
              server_name: "analytics_server",
              grantee_name: "app_reader",
              privilege_type: "USAGE",
              is_grantable: true,
            },
          ],
        };
      }

      if (sql.includes("FROM pg_default_acl")) {
        return { rows: [] };
      }

      throw new Error(`Unhandled SQL: ${sql}`);
    });

    const sqlObjects = await inspector.getCurrentSqlObjects(client, ["public"]);
    const kinds = sqlObjects.map(function (item) {
      return item.kind;
    }).sort();

    expect(kinds).toEqual([
      "constraint-trigger",
      "domain-type",
      "event-trigger",
      "foreign-server",
      "grant",
      "grant",
      "grant",
      "partition",
      "partition",
      "policy",
      "range-type",
      "role",
      "role",
      "row-level-security",
      "row-level-security",
    ]);

    expect(sqlObjects.find(function (item) {
      return item.key === "partition:public.accounts";
    })).toEqual({
      kind: "partition",
      key: "partition:public.accounts",
      name: "accounts",
      schema: "public",
      createStatement: 'CREATE TABLE "public"."accounts" (\n  "id" integer NOT NULL,\n  "region_id" integer NOT NULL,\n  CONSTRAINT "accounts_pkey" PRIMARY KEY (id)\n) PARTITION BY RANGE (region_id);',
      dropStatement: 'DROP TABLE IF EXISTS "public"."accounts" RESTRICT;',
    });

    expect(sqlObjects.find(function (item) {
      return item.key === "foreign-server:analytics_server";
    })).toEqual({
      kind: "foreign-server",
      key: "foreign-server:analytics_server",
      name: "analytics_server",
      createStatement:
        'CREATE SERVER "analytics_server" TYPE \'postgresql\' VERSION \'14\' ' +
        'FOREIGN DATA WRAPPER "postgres_fdw" OPTIONS (' +
        '"dbname" \'analytics\', "host" \'127.0.0.1\', "port" \'5432\');',
      dropStatement: 'DROP SERVER IF EXISTS "analytics_server" RESTRICT;',
      foreignServerDefinition: {
        foreignDataWrapper: "postgres_fdw",
        owner: "server_owner",
        type: "postgresql",
        version: "14",
        options: [
          { name: "dbname", value: "analytics" },
          { name: "host", value: "127.0.0.1" },
          { name: "port", value: "5432" },
        ],
      },
    });

    expect(sqlObjects.find(function (item) {
      return item.key === "grant:GRANT SELECT ON TABLE \"public\".\"users\" TO \"app_reader\";";
    })).toEqual({
      kind: "grant",
      key: 'grant:GRANT SELECT ON TABLE "public"."users" TO "app_reader";',
      name: 'GRANT SELECT ON TABLE "public"."users" TO "app_reader";',
      schema: "public",
      createStatement: 'GRANT SELECT ON TABLE "public"."users" TO "app_reader";',
      dropStatement:
        'REVOKE SELECT ON TABLE "public"."users" FROM "app_reader" RESTRICT;',
      grantDefinition: {
        objectType: "TABLE",
        objectName: "users",
        schema: "public",
        grantee: "app_reader",
        granteeIsPublic: false,
        privilege: "SELECT",
        grantable: false,
        implicitDefault: false,
      },
    });

    expect(sqlObjects.find(function (item) {
      return item.key === "row-level-security:public.users:force";
    })).toEqual({
      kind: "row-level-security",
      key: "row-level-security:public.users:force",
      name: "users",
      schema: "public",
      createStatement: 'ALTER TABLE "public"."users" FORCE ROW LEVEL SECURITY;',
      dropStatement: 'ALTER TABLE "public"."users" NO FORCE ROW LEVEL SECURITY;',
    });

    const policy = sqlObjects.find(function (item) {
      return item.key === "policy:public.users.tenant_policy";
    });
    expect(policy?.createStatement).toContain("WITH CHECK ((tenant_id > 0))");
    expect(policy?.policyDefinition).toEqual({
      command: "select",
      permissive: true,
      roles: [{ kind: "name", name: "app_reader" }],
      using:
        "(tenant_id = current_setting('app.tenant_id'::text)::integer)",
      withCheck: "(tenant_id > 0)",
    });

    expect(sqlObjects.find(function (item) {
      return item.key === "domain-type:public.email_address";
    })).toMatchObject({
      createStatement:
        'CREATE DOMAIN "public"."email_address" AS text COLLATE "pg_catalog"."C" DEFAULT \'n/a\'::text NOT NULL CONSTRAINT "email_address_check" CHECK ((position((\'@\'::text), VALUE) > 1));',
      typeDefinition: {
        kind: "domain",
        baseType: "text",
        collation: { name: "C", schema: "pg_catalog" },
        default: "'n/a'::text",
        notNull: true,
        constraints: [
          {
            name: "email_address_check",
            expression: "position(('@'::text), VALUE) > 1",
            validated: false,
          },
        ],
      },
      attributeDependents: [
        {
          schema: "public",
          relation: "users",
          attribute: "email",
          relationKind: "r",
        },
      ],
      typeDependents: [
        { schema: "public", name: "verified_email", kind: "domain" },
      ],
      routineDependents: [
        {
          schema: "public",
          name: "normalize_email",
          kind: "function",
          identityArguments: "email_address",
        },
      ],
      hasContainerColumnDependents: true,
    });

    expect(sqlObjects.find(function (item) {
      return item.key === "range-type:public.price_window";
    })).toMatchObject({
      createStatement:
        'CREATE TYPE "public"."price_window" AS RANGE (subtype = numeric, subtype_opclass = numeric_ops, collation = "C", canonical = public.price_window_canonical, subtype_diff = public.price_window_diff, multirange_type_name = "public"."price_windows");',
      typeDefinition: {
        kind: "range",
        subtype: "numeric",
        subtypeOperatorClass: { name: "numeric_ops", schema: "pg_catalog" },
        collation: { name: "C", schema: "pg_catalog" },
        canonicalFunction: { name: "price_window_canonical", schema: "public" },
        subtypeDiffFunction: { name: "price_window_diff", schema: "public" },
        multirangeTypeName: { name: "price_windows", schema: "public" },
      },
      typeDependents: [
        { schema: "public", name: "bounded_price", kind: "domain" },
      ],
    });

    expect(sqlObjects.find(function (item) {
      return item.key === "role:app_reader";
    })).toMatchObject({
      createStatement:
        'CREATE ROLE "app_reader" WITH NOLOGIN NOSUPERUSER NOCREATEDB ' +
        'NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS CONNECTION LIMIT 5;',
      roleDefinition: {
        login: false,
        superuser: false,
        createDatabase: false,
        createRole: false,
        inherit: false,
        replication: false,
        bypassRowLevelSecurity: false,
        connectionLimit: 5,
      },
    });
    expect(sqlObjects.find(function (item) {
      return item.key === "role:app_user";
    })).toMatchObject({
      kind: "role",
      roleDefinition: { login: true },
    });

    expect(sqlObjects.find(function (item) {
      return item.key === "grant:GRANT USAGE ON SCHEMA \"public\" TO \"app_reader\";";
    })?.dropStatement).toBe(
      'REVOKE USAGE ON SCHEMA "public" FROM "app_reader" RESTRICT;'
    );

    expect(sqlObjects.find(function (item) {
      return item.key === "grant:GRANT USAGE ON FOREIGN SERVER \"analytics_server\" TO \"app_reader\";";
    })).toMatchObject({
      createStatement:
        'GRANT USAGE ON FOREIGN SERVER "analytics_server" TO "app_reader" WITH GRANT OPTION;',
      dropStatement:
        'REVOKE USAGE ON FOREIGN SERVER "analytics_server" FROM "app_reader" RESTRICT;',
      grantDefinition: { grantable: true, implicitDefault: false },
    });
  });

  test("skips extension-owned relation grants", async function () {
    const inspector = new DatabaseInspector();
    const client = createClient(function (sql, params) {
      if (sql.includes("aclexplode(c.relacl)")) {
        expect(params).toEqual([["public"]]);
        expect(sql).toContain("LEFT JOIN pg_depend d ON d.objid = c.oid AND d.deptype = 'e'");
        expect(sql).toContain("AND d.objid IS NULL");
        return { rows: [] };
      }

      if (sql.includes("aclexplode(n.nspacl)")) {
        return { rows: [] };
      }

      if (sql.includes("aclexplode(s.srvacl)")) {
        return { rows: [] };
      }

      if (sql.includes("FROM pg_default_acl")) {
        return { rows: [] };
      }

      if (sql.includes("pg_get_partkeydef")) {
        return { rows: [] };
      }

      if (sql.includes("c.relispartition")) {
        return { rows: [] };
      }

      if (sql.includes("relrowsecurity")) {
        return { rows: [] };
      }

      if (sql.includes("FROM pg_policy")) {
        return { rows: [] };
      }

      if (sql.includes("t.typtype = 'd'")) {
        return { rows: [] };
      }

      if (sql.includes("FROM pg_range")) {
        return { rows: [] };
      }

      if (sql.includes("srvoptions as server_options")) {
        return { rows: [] };
      }

      if (sql.includes("t.tgconstraint <> 0")) {
        return { rows: [] };
      }

      if (sql.includes("FROM pg_event_trigger")) {
        return { rows: [] };
      }

      if (sql.includes("FROM pg_roles")) {
        return { rows: [] };
      }

      throw new Error(`Unhandled SQL: ${sql}`);
    });

    const sqlObjects = await inspector.getCurrentSqlObjects(client, ["public"]);

    expect(sqlObjects).toEqual([]);
  });

  test("preserves privileges outside the portable managed contract", async function () {
    const inspector = new DatabaseInspector() as any;
    const client = createClient(function (sql) {
      if (sql.includes("aclexplode(c.relacl)")) {
        return {
          rows: [{
            schema_name: "public",
            object_name: "accounts",
            object_type: "TABLE",
            grantee_name: "reader",
            grantee_is_public: false,
            privilege_type: "MAINTAIN",
            is_grantable: false,
          }],
        };
      }
      if (sql.includes("aclexplode(n.nspacl)")) {
        return {
          rows: [{
            schema_name: "public",
            grantee_name: "reader",
            grantee_is_public: false,
            privilege_type: "SELECT",
            is_grantable: false,
          }],
        };
      }
      if (sql.includes("aclexplode(s.srvacl)")) {
        return {
          rows: [{
            server_name: "analytics",
            grantee_name: "reader",
            grantee_is_public: false,
            privilege_type: "CONNECT",
            is_grantable: false,
          }],
        };
      }
      throw new Error(`Unhandled SQL: ${sql}`);
    });

    expect(await inspector.getCurrentGrantObjects(client, ["public"])).toEqual([]);
  });
});
