import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import type { Client } from "pg";
import { PullVerificationError } from "../types/errors";
import { Logger } from "../utils/logger";
import { cleanDatabase, createTestClient, createTestSchemaService } from "./utils";

const SCHEMA = "pull_contract";
const READER_ROLE = "pull_contract_reader";

async function dropReaderRole(client: Client): Promise<void> {
  const result = await client.query("SELECT 1 FROM pg_roles WHERE rolname = $1", [
    READER_ROLE,
  ]);
  if (result.rows.length > 0) {
    await client.query(`DROP ROLE ${READER_ROLE}`);
  }
}

async function createExistingDatabase(client: Client): Promise<void> {
  await client.query(`CREATE ROLE ${READER_ROLE}`);
  await client.query(`
    CREATE SCHEMA ${SCHEMA};
    CREATE TYPE ${SCHEMA}.status AS ENUM ('draft', 'published');
    CREATE TYPE ${SCHEMA}.address AS (street text, city text);
    CREATE DOMAIN ${SCHEMA}.positive_int AS integer CHECK (VALUE > 0);
    CREATE SEQUENCE ${SCHEMA}.ticket_numbers START 100;

    CREATE TABLE ${SCHEMA}.authors (
      id serial PRIMARY KEY,
      email varchar(255) NOT NULL UNIQUE,
      status ${SCHEMA}.status NOT NULL DEFAULT 'draft',
      home ${SCHEMA}.address,
      rating ${SCHEMA}.positive_int,
      ticket bigint NOT NULL DEFAULT nextval('${SCHEMA}.ticket_numbers'),
      bio text,
      created_at timestamptz NOT NULL DEFAULT now()
    );
    ALTER SEQUENCE ${SCHEMA}.ticket_numbers OWNED BY ${SCHEMA}.authors.ticket;
    ALTER TABLE ${SCHEMA}.authors ALTER COLUMN bio SET STORAGE EXTERNAL;

    CREATE TABLE ${SCHEMA}.posts (
      id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      author_id integer NOT NULL REFERENCES ${SCHEMA}.authors (id) ON DELETE CASCADE,
      title text NOT NULL,
      body text,
      CONSTRAINT title_present CHECK (length(title) > 0)
    );
    CREATE INDEX posts_author_idx ON ${SCHEMA}.posts (author_id) WHERE body IS NOT NULL;

    CREATE FUNCTION ${SCHEMA}.normalize_title() RETURNS trigger LANGUAGE plpgsql AS $fn$
    BEGIN
      NEW.title := trim(NEW.title);
      RETURN NEW;
    END
    $fn$;
    CREATE FUNCTION ${SCHEMA}.positive(value integer) RETURNS boolean
      LANGUAGE sql IMMUTABLE LEAKPROOF STRICT PARALLEL SAFE COST 5
      AS $fn$ SELECT value > 0 $fn$;
    CREATE FUNCTION ${SCHEMA}.author_ids() RETURNS SETOF integer
      LANGUAGE sql STABLE SECURITY DEFINER ROWS 20
      AS $fn$ SELECT id FROM ${SCHEMA}.authors $fn$;
    CREATE TRIGGER posts_normalize BEFORE INSERT OR UPDATE ON ${SCHEMA}.posts
      FOR EACH ROW EXECUTE FUNCTION ${SCHEMA}.normalize_title();

    CREATE VIEW ${SCHEMA}.z_visible_posts AS
      SELECT id, title, body FROM ${SCHEMA}.posts WHERE body IS NOT NULL;
    CREATE VIEW ${SCHEMA}.a_published_titles AS
      SELECT id, title FROM ${SCHEMA}.z_visible_posts;
    CREATE MATERIALIZED VIEW ${SCHEMA}.author_counts AS
      SELECT author_id, count(*) AS n FROM ${SCHEMA}.posts GROUP BY author_id;

    COMMENT ON TABLE ${SCHEMA}.authors IS 'people who write';
    COMMENT ON COLUMN ${SCHEMA}.posts.title IS 'headline';
    ALTER TABLE ${SCHEMA}.posts ENABLE ROW LEVEL SECURITY;
    CREATE POLICY readable_posts ON ${SCHEMA}.posts FOR SELECT USING (author_id > 0);
    GRANT USAGE ON SCHEMA ${SCHEMA} TO ${READER_ROLE};
    GRANT SELECT ON ${SCHEMA}.posts TO ${READER_ROLE};
  `);
}

async function getPublicSchemaComment(client: Client): Promise<string | null> {
  const result = await client.query<{ comment: string | null }>(
    "SELECT obj_description('public'::regnamespace, 'pg_namespace') AS comment"
  );
  return result.rows[0]?.comment ?? null;
}

async function setPublicSchemaComment(
  client: Client,
  comment: string | null
): Promise<void> {
  await client.query(
    comment === null
      ? "COMMENT ON SCHEMA public IS NULL"
      : `COMMENT ON SCHEMA public IS ${client.escapeLiteral(comment)}`
  );
}

describe("PostgreSQL pull", function () {
  let client!: Client;
  let publicSchemaComment: string | null = null;

  beforeEach(async function () {
    client = await createTestClient();
    await cleanDatabase(client, ["public", SCHEMA]);
    await dropReaderRole(client);
    publicSchemaComment = await getPublicSchemaComment(client);
    await setPublicSchemaComment(client, null);
  });

  afterEach(async function () {
    if (!client) {
      return;
    }
    try {
      await cleanDatabase(client, ["public", SCHEMA]);
      await dropReaderRole(client);
      await setPublicSchemaComment(client, publicSchemaComment);
    } finally {
      await client.end();
    }
  });

  test("reproduces an existing database as a verified desired schema", async function () {
    await createExistingDatabase(client);
    const service = createTestSchemaService();

    const pulled = await service.pull([SCHEMA]);

    expect(pulled.sql).toStartWith("-- Generated by terradb pull");
    expect(pulled.sql).toContain('"id" SERIAL NOT NULL');
    expect(pulled.sql).toContain('"id" bigint GENERATED ALWAYS AS IDENTITY,');
    expect(pulled.sql).toContain('"bio" text STORAGE EXTERNAL');
    expect(pulled.sql).toContain(`OWNED BY ${SCHEMA}.authors.ticket;`);
    expect(pulled.sql).toContain(
      "LANGUAGE sql IMMUTABLE PARALLEL SAFE LEAKPROOF STRICT COST 5;"
    );
    expect(pulled.sql).toContain("LANGUAGE sql STABLE SECURITY DEFINER ROWS 20;");
    expect(pulled.sql).not.toContain("ALTER SEQUENCE");
    expect(pulled.sql).not.toContain("CREATE ROLE");
    expect(pulled.sql.indexOf('"z_visible_posts" ("id"')).toBeLessThan(
      pulled.sql.indexOf('"a_published_titles" ("id"')
    );
    expect(pulled.statements.length).toBeGreaterThan(10);

    expect((await service.plan(pulled.sql, [SCHEMA])).hasChanges).toBe(false);
  });

  test("recreates the same schema from a pulled file and pulls it back unchanged", async function () {
    await createExistingDatabase(client);
    const service = createTestSchemaService();
    const pulled = await service.pull([SCHEMA]);

    await client.query(`DROP SCHEMA ${SCHEMA} CASCADE`);
    await service.apply(pulled.sql, [SCHEMA], true);

    expect((await service.plan(pulled.sql, [SCHEMA])).hasChanges).toBe(false);
    expect((await service.pull([SCHEMA])).sql).toBe(pulled.sql);

    await client.query(
      `INSERT INTO ${SCHEMA}.authors (email) VALUES ('writer@example.com')`
    );
    const inserted = await client.query(
      `SELECT id, ticket, status::text FROM ${SCHEMA}.authors`
    );
    expect(inserted.rows).toEqual([{ id: 1, ticket: "100", status: "draft" }]);
  });

  test("reproduces partitioned tables with identity columns", async function () {
    await client.query(`
      CREATE TABLE pull_events (
        id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 7 INCREMENT BY 3),
        bucket integer NOT NULL,
        CONSTRAINT pull_events_key UNIQUE (id, bucket)
      ) PARTITION BY RANGE (bucket);
      CREATE TABLE pull_events_low PARTITION OF pull_events FOR VALUES FROM (0) TO (100);
    `);
    const service = createTestSchemaService();
    const pulled = await service.pull(["public"]);
    expect(pulled.sql).not.toContain("LOGGED");

    await client.query("DROP TABLE pull_events");
    await service.apply(pulled.sql, ["public"], true);
    expect((await service.plan(pulled.sql)).hasChanges).toBe(false);
    const inserted = await client.query(
      "INSERT INTO pull_events (bucket) VALUES (5) RETURNING id"
    );
    expect(inserted.rows[0].id).toBe(7);
  });

  test("does not print planner progress while pulling", async function () {
    await client.query(`
      CREATE TABLE pull_quiet (id integer PRIMARY KEY);
      CREATE VIEW pull_quiet_ids AS SELECT id FROM pull_quiet;
      COMMENT ON TABLE pull_quiet IS 'quiet';
    `);
    const service = createTestSchemaService();
    const wasSilent = Logger.isSilent();
    const originalLog = console.log;
    const lines: unknown[][] = [];
    Logger.setSilent(false);
    console.log = function capture(...args: unknown[]) {
      lines.push(args);
    };
    try {
      await service.pull(["public"]);
      expect(Logger.isSilent()).toBe(false);
    } finally {
      console.log = originalLog;
      Logger.setSilent(wasSilent);
    }
    expect(lines).toEqual([]);
  });

  test("pulls an empty managed schema as a header-only file", async function () {
    const service = createTestSchemaService();
    const pulled = await service.pull(["public"]);

    expect(pulled.statements).toEqual([]);
    expect(pulled.sql).toBe(
      "-- Generated by terradb pull from a PostgreSQL database.\n" +
        "-- Managed schemas: public\n" +
        "-- Verified: planning this file against the source database produces no changes.\n"
    );
  });

  test("omits comments and privileges when they are unmanaged", async function () {
    await createExistingDatabase(client);
    const service = createTestSchemaService();

    const pulled = await service.pull([SCHEMA], {
      manageComments: false,
      managePrivileges: false,
    });

    expect(pulled.sql).not.toContain("COMMENT ON");
    expect(pulled.sql).not.toContain("GRANT");
    expect(
      (await service.plan(pulled.sql, [SCHEMA], {
        manageComments: false,
        managePrivileges: false,
      })).hasChanges
    ).toBe(false);
  });

  test("fails verification when the generated schema cannot be parsed or validated", async function () {
    await client.query("CREATE TABLE pull_kept (id integer PRIMARY KEY)");
    const service = createTestSchemaService();
    const provider = (service as any).provider;
    const parseSchema = provider.parseSchema.bind(provider);
    const validateSchema = provider.validateSchema.bind(provider);

    provider.parseSchema = async function rejectSchema() {
      throw new Error("unsupported statement");
    };
    const parseError = await service.pull(["public"]).catch(function capture(caught) {
      return caught;
    });
    expect(parseError).toBeInstanceOf(PullVerificationError);
    expect(parseError.message).toBe(
      "The generated schema could not be parsed as a desired schema: unsupported statement"
    );
    expect(parseError.statements).toEqual([]);

    provider.parseSchema = parseSchema;
    provider.validateSchema = function rejectValidation() {
      return {
        valid: false,
        errors: [{ code: "UNSUPPORTED", message: "not expressible" }],
        warnings: [],
      };
    };
    const validationError = await service.pull(["public"]).catch(function capture(caught) {
      return caught;
    });
    expect(validationError).toBeInstanceOf(PullVerificationError);
    expect(validationError.message).toBe(
      "The generated schema failed validation for the source database"
    );
    expect(validationError.statements).toEqual(["UNSUPPORTED: not expressible"]);

    provider.validateSchema = validateSchema;
    expect((await service.pull(["public"])).statements).toHaveLength(1);
  });

  test("fails verification instead of returning a schema that implies changes", async function () {
    await client.query("CREATE TABLE pull_kept (id integer PRIMARY KEY)");
    await client.query("CREATE TABLE pull_lost (id integer PRIMARY KEY)");
    const service = createTestSchemaService();
    const provider = (service as any).provider;
    const parseSchema = provider.parseSchema.bind(provider);
    provider.parseSchema = async function dropOneTable(sql: string, filePath?: string) {
      const parsed = await parseSchema(sql, filePath);
      return {
        ...parsed,
        tables: parsed.tables.filter(function isKept(table: { name: string }) {
          return table.name !== "pull_lost";
        }),
      };
    };

    const error = await service.pull(["public"]).catch(function capture(caught) {
      return caught;
    });

    expect(error).toBeInstanceOf(PullVerificationError);
    expect(error.code).toBe("PULL_VERIFICATION_ERROR");
    expect(error.statements.some(function dropsLostTable(statement: string) {
      return statement.includes("DROP TABLE") && statement.includes("pull_lost");
    })).toBe(true);
  });
});
