import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { Database } from "bun:sqlite";
import { SQLiteProvider } from "../../providers/sqlite";
import { SchemaService } from "../../core/schema/service";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

const EXISTING_SCHEMA = [
  `CREATE TABLE authors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE COLLATE NOCASE,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
  ) STRICT`,
  `CREATE TABLE posts (
    id INTEGER PRIMARY KEY,
    author_id INTEGER NOT NULL REFERENCES authors(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (length(title) > 0),
    body TEXT,
    slug TEXT GENERATED ALWAYS AS (lower(title)) VIRTUAL
  )`,
  "CREATE INDEX posts_author_idx ON posts (author_id) WHERE body IS NOT NULL",
  "CREATE VIEW recent_posts AS SELECT id, title FROM posts ORDER BY id DESC LIMIT 10",
  `CREATE TRIGGER posts_trim AFTER INSERT ON posts BEGIN
    UPDATE posts SET title = trim(NEW.title) WHERE id = NEW.id;
  END`,
  "CREATE VIRTUAL TABLE documents USING fts5(title, body)",
];

describe("SQLite pull", () => {
  let dbPath: string;
  let copyPath: string;

  beforeEach(() => {
    const suffix = `${Date.now()}-${Math.floor(Math.random() * 1000000)}`;
    dbPath = path.join(os.tmpdir(), `terradb-pull-${suffix}.db`);
    copyPath = path.join(os.tmpdir(), `terradb-pull-copy-${suffix}.db`);
  });

  afterEach(() => {
    for (const file of [dbPath, copyPath]) {
      try { if (fs.existsSync(file)) fs.unlinkSync(file); } catch {}
    }
  });

  function createService(filename: string): SchemaService {
    return new SchemaService(new SQLiteProvider(), { dialect: "sqlite", filename });
  }

  test("reproduces an existing database and recreates it losslessly", async () => {
    const db = new Database(dbPath);
    for (const statement of EXISTING_SCHEMA) {
      db.run(statement);
    }
    db.close();

    const source = createService(dbPath);
    const pulled = await source.pull();

    expect(pulled.sql).toStartWith(
      "-- Generated by terradb pull from a SQLite database.\n"
    );
    expect(pulled.sql).not.toContain("Managed schemas");
    expect(pulled.sql).toContain("AUTOINCREMENT");
    expect(pulled.sql).toContain("USING fts5(title, body)");
    expect(pulled.sql).not.toContain("documents_data");
    expect((await source.plan(pulled.sql)).hasChanges).toBe(false);

    const copy = createService(copyPath);
    await copy.apply(pulled.sql, ["public"], true);
    expect((await copy.plan(pulled.sql)).hasChanges).toBe(false);
    expect((await copy.pull()).sql).toBe(pulled.sql);

    const sourceObjects = new Database(dbPath)
      .query("SELECT type, name, sql FROM sqlite_schema ORDER BY type, name")
      .all();
    const copiedObjects = new Database(copyPath)
      .query("SELECT type, name, sql FROM sqlite_schema ORDER BY type, name")
      .all();
    expect(copiedObjects.map((row: any) => [row.type, row.name])).toEqual(
      sourceObjects.map((row: any) => [row.type, row.name])
    );
  });

  test("pulls an empty database as a header-only file", async () => {
    const pulled = await createService(dbPath).pull();

    expect(pulled.statements).toEqual([]);
    expect(pulled.sql).toBe(
      "-- Generated by terradb pull from a SQLite database.\n" +
        "-- Verified: planning this file against the source database produces no changes.\n"
    );
  });
});
