import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { Database } from "bun:sqlite";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

function readStream(stream: ReadableStream<Uint8Array> | null): Promise<string> {
  if (!stream) return Promise.resolve("");
  return new Response(stream).text();
}

async function runCli(args: string[], extraEnv: Record<string, string> = {}) {
  const env: Record<string, string> = {};
  for (const [key, value] of Object.entries(process.env)) {
    if (typeof value === "string") {
      env[key] = value;
    }
  }
  for (const [key, value] of Object.entries(extraEnv)) {
    env[key] = value;
  }

  const proc = Bun.spawn([process.execPath, "run", "src/index.ts", ...args], {
    cwd: process.cwd(),
    env,
    stdout: "pipe",
    stderr: "pipe",
  });

  const [stdout, stderr, exitCode] = await Promise.all([
    readStream(proc.stdout),
    readStream(proc.stderr),
    proc.exited,
  ]);

  return { exitCode, stdout, stderr };
}

const EXPECTED_SQL =
  "-- Generated by terradb pull from a SQLite database.\n" +
  "-- Verified: planning this file against the source database produces no changes.\n" +
  "\n" +
  "CREATE TABLE \"notes\" (id INTEGER PRIMARY KEY, body TEXT NOT NULL);\n" +
  "\n" +
  "CREATE INDEX notes_body_idx ON notes (body);\n";

describe("CLI pull contract", () => {
  let directory: string;
  let databasePath: string;

  beforeEach(async () => {
    directory = await mkdtemp(join(tmpdir(), "terradb-pull-cli-"));
    databasePath = join(directory, "source.db");
    const db = new Database(databasePath);
    db.run("CREATE TABLE notes (id INTEGER PRIMARY KEY, body TEXT NOT NULL)");
    db.run("CREATE INDEX notes_body_idx ON notes (body)");
    db.close();
  });

  afterEach(async () => {
    await rm(directory, { recursive: true, force: true });
  });

  test("lists pull in root help and documents its flags", async () => {
    const root = await runCli(["--help"], { DATABASE_URL: "" });
    expect(root.exitCode).toBe(0);
    expect(root.stdout).toContain("pull [options]");

    const help = await runCli(["pull", "--help"], { DATABASE_URL: "" });
    expect(help.exitCode).toBe(0);
    expect(help.stderr.trim()).toBe("");
    for (const flag of [
      "--file <file>",
      "--overwrite",
      "--url <url>",
      "--schema <schema>",
      "--ignore-privileges",
      "--ignore-comments",
      "--ignore-constraint-validation",
      "--format <format>",
    ]) {
      expect(help.stdout).toContain(flag);
    }
  });

  test("writes the verified schema to standard output by default", async () => {
    const result = await runCli(["pull", "--url", databasePath]);

    expect(result.exitCode).toBe(0);
    expect(result.stderr).toBe("");
    expect(result.stdout).toBe(EXPECTED_SQL);
  });

  test("writes a schema file that plans no changes and refuses to overwrite it", async () => {
    const schemaPath = join(directory, "schema.sql");
    const written = await runCli(["pull", "--url", databasePath, "-f", schemaPath, "--no-color"]);

    expect(written.exitCode).toBe(0);
    expect(written.stdout.trim()).toBe(
      `Wrote 2 statement(s) to ${schemaPath}; planning it against this database produces no changes`
    );
    expect(await readFile(schemaPath, "utf-8")).toBe(EXPECTED_SQL);

    const plan = await runCli(["plan", "--url", databasePath, "-f", schemaPath, "--format", "json"]);
    expect(plan.exitCode).toBe(0);
    expect(JSON.parse(plan.stdout).hasChanges).toBe(false);

    await writeFile(schemaPath, "-- hand edits\n", "utf-8");
    const refused = await runCli(["pull", "--url", databasePath, "-f", schemaPath, "--format", "json"]);
    expect(refused.exitCode).toBe(1);
    expect(JSON.parse(refused.stdout).error).toMatchObject({
      code: "VALIDATION_ERROR",
      message: `Refusing to overwrite existing file '${schemaPath}'. Use --overwrite to replace it`,
    });
    expect(await readFile(schemaPath, "utf-8")).toBe("-- hand edits\n");

    const replaced = await runCli(["pull", "--url", databasePath, "-f", schemaPath, "--overwrite"]);
    expect(replaced.exitCode).toBe(0);
    expect(await readFile(schemaPath, "utf-8")).toBe(EXPECTED_SQL);
  });

  test("emits a stable JSON document", async () => {
    const schemaPath = join(directory, "schema.sql");
    const result = await runCli([
      "pull",
      "--url",
      databasePath,
      "-f",
      schemaPath,
      "--format",
      "json",
    ]);

    expect(result.exitCode).toBe(0);
    expect(result.stderr).toBe("");
    expect(result.stdout).toBe(
      `${JSON.stringify({
        schemaVersion: 2,
        command: "pull",
        dialect: "sqlite",
        file: schemaPath,
        schemas: ["public"],
        statementCount: 2,
        sql: EXPECTED_SQL,
      })}\n`
    );
    expect(existsSync(schemaPath)).toBe(true);
  });

  test("does not create a file when the source database is unreachable", async () => {
    const schemaPath = join(directory, "schema.sql");
    const result = await runCli([
      "pull",
      "--url",
      "postgres://nobody:nothing@127.0.0.1:1/missing?connect_timeout=1",
      "-f",
      schemaPath,
      "--format",
      "json",
    ]);

    expect(result.exitCode).toBe(1);
    expect(JSON.parse(result.stdout).error.code).toBeString();
    expect(existsSync(schemaPath)).toBe(false);
  });
});
